### ISSUE TITLE
Got Http response code 500

### ISSUE THREAD

**Issue by GabrielAugustoTI** [blockcypher/php-client#23] opened 2016-11-13 19:47 UTC
Got Http response code 500 when accessing https://api.blockcypher.com/v1/btc/main/txs/micro?token=

{"error": "Error building micro transaction: Not enough funds in 0 inputs to pay for 1 outputs, missing -7000."}
But input has a unconfirmed transaction to pay 1 output;..
https://live.blockcypher.com/btc/tx/d665d9b0706dae793f4a98ee78ed9e1bb987635295dcab55b8923d4add2df7ab/

http://prntscr.com/d6u35y

**Comment by GabrielAugustoTI** [comment] 2016-11-13 20:14
Unconfirmed transaction can't used for micro transactions! Please fix!

**Comment by acityinohio** [comment] 2016-11-14 19:09
Without an available and confirmed UTXO, we cannot generate the transaction; to the API, it looks like there are no funds available, hence the error message.

Longer term, we may start looking into payment channel-based solutions for microtransactions in the future, which could reduce these sorts of headaches. We're hoping something like the Lightning Network could help with this.

**Comment by josecelano** [comment] 2016-11-14 23:00
Thanks @acityinohio @GabrielAugustoTI I think we can close this issue.

**Comment by josecelano** [comment] 2016-11-14 23:01
Thanks @acityinohio @GabrielAugustoTI I think we can close this issue.

**Closed by josecelano** 2016-11-14 23:01 UTC
Labels: help wanted
